fn main() {
    println!("cargo:rerun-if-changed=src/weak_on_trace.c");

    // The ARM target allows for creating a weak assembly label. Therefore,
    // it doesn't need the symbol generated by weak_on_trace.c. To not have
    // to install an additional compiler for arm, use that instead
    if std::env::var("CARGO_CFG_TARGET_ARCH").unwrap() != "arm" {
        cc::Build::new()
            .file("src/weak_on_trace.c")
            .compile("weak_on_trace");
    }
}
